SELECT * FROM DEPARTMENTS;

SELECT
   DEPARTMENT_ID, LOCATION_ID
FROM DEPARTMENTS;

SELECT DEPARTMENT_ID, LOCATION_ID
FROM employees;

SELECT  LOCATION_ID, DEPARTMENT_ID
FROM DEPARTMENTS;

SELECT SALARY,EMAIL,FIRST_NAME
FROM EMPLOYEES;

SELECT LAST_NAME, SALARY, SALARY + 300
FROM EMPLOYEES;

SELECT FIRST_NAME, SALARY, SALARY + 500
FROM EMPLOYEES;

SELECT LAST_NAME, SALARY, SALARY * 12 ANNUAL
FROM EMPLOYEES; --FOR ONE WORD DON'T USE QUOTATION

SELECT LAST_NAME, SALARY, SALARY * 12 "ANNUAL_SALARY" 
FROM EMPLOYEES; --FOR MULTIPLE WORD

SELECT LAST_NAME, SALARY, SALARY * 12 AS "ANNUAL_SALARY"
FROM EMPLOYEES; --YOU CAN USE AS

SELECT LAST_NAME, SALARY, (SALARY *12)/12 MONTHLY_SALARY
FROM EMPLOYEES;

SELECT LAST_NAME, SALARY, (SALARY *12)/12 MONTHLY_SALARY, (SALARY *12)/2 SIX_MONTH
FROM EMPLOYEES;

SELECT LAST_NAME, JOB_ID, SALARY, COMMISSION_PCT
FROM EMPLOYEES;

SELECT LAST_NAME, JOB_ID, SALARY, COMMISSION_PCT * 10
FROM EMPLOYEES;

--CREATE NEW TABLE

CREATE TABLE IDB_STU(
   STU_ID INT PRIMARY KEY,
   SUT_NAME VARCHAR2(30) NOT NULL,
   DOB DATE
   

);


SELECT * FROM IDB_STU;

SELECT LAST_NAME || 'IS A' ||JOB_ID 
  AS "EMPLOYEE DETAILS"
FROM EMPLOYEES;

SELECT LAST_NAME || 'IS A' || JOB_ID AS "EMPLOYEE DETAILS"
FROM EMPLOYEES;

SELECT DEPARTMENT_ID
FROM EMPLOYEES; --DUPLICATES

SELECT DISTINCT DEPARTMENT_ID
FROM EMPLOYEES; --FOR REMOVE DUPLICATES

DESC EMPLOYEES;

DESCRIBE EMPLOYEES;

SELECT * FROM EMPLOYEES
WHERE DEPARTMENT_ID=90;--FOR SEE SPECIFIC DATA

SELECT * FROM EMPLOYEES
WHERE DEPARTMENT_ID=90 OR SALARY <=15000;

SELECT * FROM EMPLOYEES
WHERE LAST_NAME='Whalen';

SELECT * FROM EMPLOYEES
WHERE HIRE_DATE='17-OCT-03';

SELECT * FROM EMPLOYEES
WHERE SALARY BETWEEN 10000 AND 15000;

SELECT * FROM EMPLOYEES
WHERE SALARY IN (10000,15000,17000);--ONLY SEE THIS THREE SALARY OUTPUTS

SELECT * FROM EMPLOYEES
WHERE FIRST_NAME LIKE 'K%n'; --(%) this sign for first names last word n

SELECT EMPLOYEE_ID, MANAGER_ID, DEPARTMENT_ID
FROM EMPLOYEES
WHERE LAST_NAME IN ('Hartstein', 'Vargas');

SELECT LAST_NAME, HIRE_DATE
FROM EMPLOYEES
WHERE HIRE_DATE LIKE '%05';

SELECT LAST_NAME, HIRE_DATE
FROM EMPLOYEES
WHERE LAST_NAME LIKE '_u%'; --for search second word u

SELECT LAST_NAME, HIRE_DATE
FROM EMPLOYEES
WHERE HIRE_DATE LIKE '___MAY%';

SELECT LAST_NAME, HIRE_DATE
FROM EMPLOYEES
WHERE (HIRE_DATE LIKE '___MAY%' AND HIRE_DATE LIKE '%07');

SELECT LAST_NAME, HIRE_DATE
FROM EMPLOYEES
WHERE NOT (HIRE_DATE LIKE '___MAY%' AND HIRE_DATE LIKE '%07');

SELECT * 
FROM EMPLOYEES
WHERE commission_pct IS NULL;

SELECT LAST_NAME, HIRE_DATE, SALARY
FROM EMPLOYEES
ORDER BY SALARY;-- FOR ASSENDING BY DEFAULT

SELECT LAST_NAME, HIRE_DATE, SALARY
FROM EMPLOYEES
ORDER BY SALARY DESC;-- FOR DECENDING ORDER

SELECT LAST_NAME, HIRE_DATE, SALARY
FROM EMPLOYEES
WHERE SALARY<=15000
ORDER BY SALARY DESC;

SELECT LAST_NAME, HIRE_DATE, SALARY
FROM EMPLOYEES
WHERE SALARY<=15000
ORDER BY 2;--FOR SHOW WHO JOIN FIRST

SELECT LAST_NAME, HIRE_DATE, SALARY
FROM EMPLOYEES
WHERE SALARY<=15000
ORDER BY 2 DESC;--FOR SHOW WHO JOIN LAST



